removing coalesce as its not needed and breaks execution
GitHub reported the following error:

Traceback (most recent call last):
  File "/home/runner/work/mma-elo-backend/mma-elo-backend/calculate_elo.py", line 127, in <module>
    ''').order('fighter_id').range(offset, offset + limit - 1).execute()
                                                               ^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/postgrest/_sync/request_builder.py", line 78, in execute
    raise APIError(r.json())
postgrest.exceptions.APIError: {'code': 'PGRST200', 'details': "Searched for a foreign key relationship between 'fighters_enriched_new' and 'COALESCE' in the schema 'public', but no matches were found.", 'hint': None, 'message': "Could not find a relationship between 'fighters_enriched_new' and 'COALESCE' in the schema cache"}
Error: Process completed with exit code 1.